---
minio_version: "RELEASE.2024-01-16T16-07-38Z"
minio_server_bin: /usr/local/bin/minio
minio_user: minio
minio_group: minio
minio_data_dir: /data
minio_config_dir: /etc/minio

minio_server_addr: ":9000"
minio_console_addr: ":9001"

minio_root_user: "minioadmin"
minio_root_password: "minioadmin"

minio_volumes: "{{ minio_data_dir }}"
minio_opts: "--console-address {{ minio_console_addr }} --address {{ minio_server_addr }}"
